### ISSUE TITLE
Trace flags to add

### ISSUE THREAD

**Issue by jobbish-sql** [ktaranov/sqlserver-kit#128]
I did a very poor job of documenting them, but there are some new trace flags here: https://orderbyselectnull.com/2018/01/09/45-new-trace-flags/

During research for that post I also found the following that were posted by someone else:

9479	https://dba.stackexchange.com/questions/141220/sql-server-2014-any-explanation-for-inconsistent-self-join-cardinality-estimate
8691	https://www.sqlservercentral.com/Forums/Topic1390297-3122-5.aspx
9415	http://www.queryprocessor.com/adaptive-join-internals/
9399	http://www.queryprocessor.com/adaptive-join-internals/
9398 	http://www.queryprocessor.com/adaptive-join-internals/
2399	https://dba.stackexchange.com/questions/149811/why-does-the-estimated-cost-of-the-same-1000-seeks-on-a-unique-index-differ-in
9410	https://support.microsoft.com/en-us/help/3167159/fix-query-runs-slowly-when-sql-server-uses-hash-aggregate-in-the-query

**Comment by ktaranov** [comment]
@jobbish-sql , great thanks for this information. Test it and add all flags in this week.

**Comment by ktaranov** [comment]
@jobbish-sql, thanks again for issue and new flags, added via https://github.com/ktaranov/sqlserver-kit/commit/8d022f38214592630e99382178f5492215fb4a84#diff-4c49ad75ed498a038b7b20763ec8d708 and https://github.com/ktaranov/sqlserver-kit/commit/09c8502e8e52b132377456325ef355214f39aa01#diff-4c49ad75ed498a038b7b20763ec8d708

**Comment by jobbish-sql** [comment]
Dima offered a new corrections and new ones. Be sure to look at the comments.

**Comment by ktaranov** [comment]
@jobbish-sql, thanks again for new flags and especially for https://orderbyselectnull.com/2018/01/16/a-method-to-find-trace-flags/
Added all new trace flags.
