### ISSUE TITLE
Glenn Berry Diagnostic Scripts Copyright

### ISSUE THREAD

**Issue by ktaranov** [ktaranov/sqlserver-kit#140]
According this comments https://github.com/ktaranov/sqlserver-kit/commit/ffc09ba013d4a7309a0533ebd37f5669d6f5c94f#commitcomment-27792716

Waiting for Glen answer.

**Comment by ktaranov** [comment]
Closed due to this reasons:

> The only request is to convey to Glen my point of view: I constantly recommend his blog and articles to all Russian-speaking colleagues and always recommending his scripts for use. The problem is that it is not always convenient for Russian-speaking users to understand which of the versions of its scripts is the last, so for their convenience (and, of course, my study), I constantly update them in our repository. And I would like to do this in the future. But if I violate the conditions for the distribution of scripts, then at any time I'm ready to add the necessary explanations to their header or in the worst case, delete them from the repository.

**Comment by sterbalr** [comment]
You might want to just publish the links to the scripts, and check/update those links periodically.

Hope that helps,

Robert Sterbal  / Technical Specialist
Omnicell, Inc.
Office: 724.741.8363
Mobile: 412.977.3526
Inspired by Care™
