### ISSUE TITLE
Add trace flag 8759

### ISSUE THREAD

**Issue by BlitzErik** [ktaranov/sqlserver-kit#146]
Trace flag 8759 will detect and write part of the query to the error log when it has been autoparameterized.

**Comment by BlitzErik** [comment]
Not yet. I've only found it referenced in one book. Wanted to log it here so I didn't forget. Gimme a couple days.

**Comment by jzabroski** [comment]
It appears to be from [The Guru's Guide to SQL Server Architecture and Internals](https://books.google.com/books?isbn=0201700476), ISBN:0201700476 - Page 466:

> The syscacheobjects table is also a good place to check for auto-parameterization. WHen SQL Server has auto-parameterized an ad hoc query, the automatically generated parameter placeholders and data types will be included at the start of the sql column in the query's rows in syscacheobjects. The query text listed in the sql column will also use these placeholders to filter the data it returns, like so:
> `(@1 smallint)SELECT * FROM [Orders] WHERE [OrderId]=@1`
> When trace flag 8759 is enabled, the first part of an auto-parameterized query is written to the SQL Server error log, as shown below.
> `SAFE auto-paramd query: (@1 smallint) SELECT * FROM [Orders] WHERE [Orderid]=@1`

**Comment by jzabroski** [comment]
@BlitzErik  What are you doing reading a 14 year old book on SQL Server? :)

**Comment by ktaranov** [comment]
@jzabroski how you are google it? Could you describe this (it will be goog help to find more information for some undocumented flags)?

**Comment by jzabroski** [comment]
I don't remember precisely how. In the words of one very senior architect
at Microsoft, I have developed very powerful filters for separating the
intellectual wheat from its chaff.

Also, I have a rare talent: photographic memory. Plus, I like reading and
having read a lot about SQL Server, I knew which books it couldn't be in.

**Comment by BlitzErik** [comment]
Yeah, using TOP prevents simple parameterization.

**Comment by ktaranov** [comment]
Cant reproduce behaviour this trace flag on SQL Server 2014 and 2017. Flag was added in list via https://github.com/ktaranov/sqlserver-kit/commit/345094462ab7bec72e926165c1fae488c3142e50
Closed today.

**Comment by jzabroski** [comment]
@ktaranov  @BlitzErik  Sorry for the late reply.  I subscribe to so many GitHub projects that sometimes I get backlogged and have to work through it.

I just re-ran your repro on SQL Server 2017 and confirm your results. I think the modern equivalent for this would be to use Extended Events.  If I had to guess, this trace flag was removed in SQL Server 2014 in alignment with Hekaton features https://en.wikipedia.org/wiki/Hekaton_(database)

In particular, Hekaton added natively compiled procedures, and the natively_compiled_proc_slow_parameter_passing extended event.  If you think about the problem of forced parameterization broadly enough, you'll consider that this Trace Flag doesn't really help you in all situations.  In addition, you can use other extended events:

1. forced_param_clause_skipped_reason
2. forced_param_statement_ignored_reason 
3. query_parameterization_data

In addition, the Query Store feature has the sys.query_store_query DMV which will tell you the type of parameterization applied to a given query.

In this sense, there is probably no real need for this.
