### ISSUE TITLE
Explicitly add Aaron Bertrand's dbo.sp_ForEachDb

### ISSUE THREAD

**Issue by jzabroski** [ktaranov/sqlserver-kit#147]
**What is the current behavior?**
Some code references this stored procedure but it doesn't exist in the repository

Examples: https://github.com/ktaranov/sqlserver-kit/search?q=dbo.sp_ForEachDb&unscoped_q=dbo.sp_ForEachDb

**Comment by jzabroski** [comment]
Why not add it to the README.md, then?

**Comment by BlitzErik** [comment]
@jzabroski If you're asking me, it's not in the README because it's in the [LICENSE](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/LICENSE.md).

**Comment by ktaranov** [comment]
Added help into stored procedure via https://github.com/ktaranov/sqlserver-kit/commit/0f010336bebc71105f78894c3292cb27498f24b4
