### ISSUE TITLE
Compute transitive closure of sys.sql_dependencies, find missing objects

### ISSUE THREAD

**Issue by jzabroski** [ktaranov/sqlserver-kit#149]
https://mssqlwiki.com/2012/05/04/copy-database-wizard-or-replication-setup-might-fail-due-to-broken-dependency/

This script is pure gold.  I've repeatedly reached out to Karthik asking permission to host it on GitHub, but he has never responded.  It does contain bugs, some of which I've [fixed in the comments](https://mssqlwiki.com/2012/05/04/copy-database-wizard-or-replication-setup-might-fail-due-to-broken-dependency/#comment-27991) and others which were left with my former employer when I left.

Some things I fixed:
* The original script assumed stored procedures could be refreshed in any order. This is only true for trivial stored procedures that *don’t reference objects that can’t be refreshed in any order*. My fix handles that scenario.
* My fix explicitly handles stored procedures and/or triggers.
* Fix the scenario where a schema-bound view is transitively referencing a broken view.

Some fixes not contained in my patch, off the top of my head:
* Common Table Expressions variables erroneously flag as false positives in this script. At my former employer, we would maintain a lookup table of Common Table Expression variables and generally exclude object names under 3 characters as bogus.
* Session-scoped temp tables and global temp tables erroneously flag as false positives in this script.

While Karthik uses it to find broken dependencies *in the context of copy database wizard or replication setup*, I used it after running database migrations to automatically rollback all migrations if the migration broke references/didn't clean up after itself.  Some people naively call sp_refreshview or sp_refreshsqlmodule over all sys.objects, but this will fail if you have circular references, which is what Karthik's original script mostly resolves.

**Comment by ktaranov** [comment]
Hi, @jzabroski .

Still testing, tomorrow will test on SQL Server 2014.

**Comment by ktaranov** [comment]
@jzabroski  Too many bugs in my enviroment, could you add here your working version?

**Comment by jzabroski** [comment]
I think I need more information from you on what bugs you are seeing, and
some explanation of your environment.

My version is more or less in the comments.

Happy to add features, as I have time. But I don't actively use this code.
It's been my dream to build out a test suite for it.

**Comment by ktaranov** [comment]
Added via af5328829642902014198434294dfb4febebdb52
