### ISSUE TITLE
Add sqlsig SQLCLR function for auto-parameterizing TextData from SQL Profiler Trace

### ISSUE THREAD

**Issue by jzabroski** [ktaranov/sqlserver-kit#150]
This code is from Itzik Ben-Gan's book on query tuning, and is largely unknown to those who have never read the book.

**Comment by BlitzErik** [comment]
This is copyright material: https://www.amazon.com/Inside-Microsoft%C2%AE-SQL-Server%C2%AE-2008/dp/0735626030

I don't think you can just add this.

**Comment by jzabroski** [comment]
What if we were to write a better one?

In my recollection, his version is not complete-complete.  It's usually "good enough" for a first pass.

Things I do to spruce up the logic:
* Call an inline table-valued function helper called dbo.TrimChars, which returns a column called FixedString that gives you a cleaned up version of TextData that has no TAB (`NCHAR(9)`), CR (`NCHAR(13)`), LF (`NCHAR(10)`) or SPACE (`NCHAR(32)`):

```sql
UPDATE tdt
SET
	TextData = itvf.FixedString
FROM dbo.TraceDataTable tdt
	CROSS APPLY dbo.TrimChars(
		TextData,
		NCHAR(9) /* TAB */ + NCHAR(13) /* CR */ + NCHAR(10) /* LF */ + NCHAR(32)
	) itvf
```

Reference: https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html

**Comment by jzabroski** [comment]
What sqlsig does is nothing remarkable. It simply looks for known operators that signal an expression of the form `lexpr op rexpr`. In fact, it assumes if it sees a valid `op rexpr` where `rexpr` is a character sequence, binary number, precise number, imprecise number, or integer. It replaces `rexpr` with `#`

**Comment by ktaranov** [comment]
@jzabroski if you want create PR and add this code to this repo - you are welcome but first you need solve all copyright questions with Itzik Ben-Gan.
