### ISSUE TITLE
Add trace flag 876 

### ISSUE THREAD

**Issue by BrentOzar** [ktaranov/sqlserver-kit#151]
From Slava Oks' tweet this week on SQL Server 2019:

https://twitter.com/slava_oks/status/1044257034361757696

> With every new #SQLServer announcement it feels like Christmas time of the year, presents for everyone, @NikoNeugebauer with #SQLServer2019 CTP 2.0, could you please try trace flag -T876 instead of -T834 for some of key CS scenarios and check performance?

https://twitter.com/slava_oks/status/1044413511466512384

> No -T876 is different beast... it turns 8k page allocations for CS segments into 2MB instead.  -T834 does exactly that as well as it pre-commits the entire sql memory with large pages which many workloads don’t really need.

**Comment by ktaranov** [comment]
@BrentOzar  Great thanks for this trace flag, 
added via https://github.com/ktaranov/sqlserver-kit/commit/7fc8ce4dbd1e52e20688e9229d06a36dd354e05f

Waiting for Niko answer to add more information and use cases.
