### ISSUE TITLE
SQL Server 2012 Diagnostic queries - problem with query -  latency per database file

### ISSUE THREAD

**Issue by alhandra** [ktaranov/sqlserver-kit#152]
Hi,
on SQL Server 2012 the query that collects the latency per database file, the governor metrics are not working in 2012.
I suggest just removing the following columns:

io_stall_queued_read_ms AS [Resource Governor Total Read IO Latency (ms)], io_stall_queued_write_ms AS [Resource Governor Total Write IO Latency (ms)]

Regards,
Hugo Alhandra

**Comment by ktaranov** [comment]
Great thanks, Hugo. Fixed via https://github.com/ktaranov/sqlserver-kit/commit/16f585cd310491c7a7f32f4208184b0da03f5175

https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql?view=sql-server-2017
