### ISSUE TITLE
Find more tools and utilities

### ISSUE THREAD

**Issue by ktaranov** [ktaranov/sqlserver-kit#154]
Check this tools lists:
 - [ ] https://www.sqlshack.com/free-ms-sql-server-tools/
 - [ ] https://www.sqlshack.com/sql-azure-tools/
 - [ ] https://www.sqlshack.com/sql-formatting-tools
 - [ ] http://www.ilovefreesoftware.com/23/featured/online-database-diagram-tool-create-design-database-schema-free.html
 - [ ] https://sqlgrease.com/

**Comment by Walcar** [comment]
Grate job with Get_SQL_Server_Backup_Directory.sql, but doesnt work in linux version, any idea of how to get the default back up directory, like we get:
Select SERVERPROPERTY('INSTANCEDEFAULTDATAPATH')],
SERVERPROPERTY('INSTANCEDEFAULTLOGPATH');

Thanks !!

**Comment by ktaranov** [comment]
Hi, @Walcar . Could you provide full output for your instance: `SELECT @@VERSION;`

**Comment by Walcar** [comment]
Hi, @ktaranov.
This is the result of Select @@VERSION:

Microsoft SQL Server 2017 (RTM-CU7) (KB4229789) - 14.0.3026.27 (X64)   May 10 2018 12:38:11   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)
