### ISSUE TITLE
dbo.sp_DBPermissions.sql third result set ambiguous return order

### ISSUE THREAD

**Issue by jzabroski** [ktaranov/sqlserver-kit#156]
I have been at my wit's end trying to understand an issue in production where I'm getting a SELECT DENIED error on an UPDATE statement, and it works fine in BETA environment.. so I'm using Ken Fisher's wonderful sp_DBPermissions to try to compare one by one each permission to see if somehow something got deployed incorrectly.

While doing this, I noticed that it's ordered by grantee_name and object_name but NOT permission_name, leading to situations where VIEW DEFINITION and EXECUTE permissions on two different servers might be output in different order.

For my use case, I was copy-pasting the output into EXCEL and running a simple =I3=S3 column sanity check operation.

**Comment by ktaranov** [comment]
@jzabroski  Thanks for suggestion, I will try add ordering on next week.

**Comment by jzabroski** [comment]
I'll try to patch it as well... I feel I am going to try a server reboot as I've tried everything so far and no such luck figuring out why this is happening.  Have you ever hard a problem like this?  I checked column level privileges, CONTROL permissions, etc.

**Comment by ktaranov** [comment]
Moved to https://github.com/sqlstudent144/SQL-Server-Scripts/issues/5
