### ISSUE TITLE
sql server object permissions with username and group details

### ISSUE THREAD

**Issue by Iamseshu1983** [ktaranov/sqlserver-kit#157]
Looking to find for one object full permissions including the user name and its windows domain group detials. any suggestions? Tried with fn_my_permissions. Its giving only kind of access.

**Comment by ktaranov** [comment]
More details please: version of sql server, columns output example, type of object (table, procedure , etc). For permission details I highly recommend using awesome stored procedures written by Kenneth Fisher:
https://github.com/ktaranov/sqlserver-kit/blob/master/Stored_Procedure/dbo.sp_SrvPermissions.sql
https://github.com/ktaranov/sqlserver-kit/blob/master/Stored_Procedure/dbo.sp_DBPermissions.sql

**Comment by Iamseshu1983** [comment]
cool..seems let me try it thanks.

**Comment by Iamseshu1983** [comment]
No luck its not providing function permissions to a specific one. i can see the function exist in the system. the system is running with 2016. Just need information for one function who are all having access to run the function and need to compare the same with other environment.

**Comment by ktaranov** [comment]
Could you post minimal example script to reproduce your issue? Create statement for function and grant statements for it?

**Comment by Iamseshu1983** [comment]
found that there is a group which is having higher permission. Thanks for the help.
