### ISSUE TITLE
Add Trace Flag 9198 to doc

### ISSUE THREAD

**Issue by erikdarlingdata** [ktaranov/sqlserver-kit#161]
Referenced [here](https://sqlperformance.com/2019/09/sql-performance/nested-loops-joins-performance-spools)

> Undocumented trace flag 9198 can be used to disable lazy index performance spools specifically. You may still get a lazy table or row count spool instead (with or without sort optimization), depending on costing.

**Comment by ktaranov** [comment]
Great thanks! Added via https://github.com/ktaranov/sqlserver-kit/commit/dd9a61eb5bdb198be208b8ee63e3a0c60541f936
