### ISSUE TITLE
Add naming convention for Linked Servers

### ISSUE THREAD

**Issue by iSatishYadav** [ktaranov/sqlserver-kit#166]

**Comment by ktaranov** [comment]
Hi @iSatishYadav , thanks for idea. Do you have any recommendation about naming convention for Linked Servers?

**Comment by Stephen005** [comment]
Alternative for lodash and underscore 
https://onlinedevtools.in/lodash_underscore_alternative

Format your SQL queries online
https://onlinedevtools.in/online/sqlformatter

Find your npm package size and dependency
https://onlinedevtools.in/online/npmpackageanalyzer

Convert your curl to HTTP request online
https://onlinedevtools.in/curl

explain and create cronjob online
https://onlinedevtools.in/crontab

Latest, useful trending programming and development related blogs
https://onlinedevtools.in/devnews

Compare your text file online
https://diffviewer.onlinedevtools.in

**Comment by ktaranov** [comment]
Added via 81427f191e5ba4d1536ddde8bfd29104e4933392. Thanks for suggestion.
