### ISSUE TITLE
Author incorrect

### ISSUE THREAD

**Issue by brettshearer** [ktaranov/sqlserver-kit#169]
I (Brett Shearer) did not write the article attributed to me.

**Comment by ktaranov** [comment]
I will fix it tomorrow, thanks for your issue.

**Comment by ktaranov** [comment]
Fixed via https://github.com/ktaranov/sqlserver-kit/commit/4cecaa62eddba5bf43ac5bb6ed852f521ba1201a
Thanks for your issue.
