### ISSUE TITLE
New home for "Learning Extended Events in 60 Days"

### ISSUE THREAD

**Issue by bogdandb** [ktaranov/sqlserver-kit#172]
It seems that the course "Learning Extended Events in 60 Days" has a new landing page (see [here](https://jasonbrimhall.info/2020/05/18/extended-events-gets-a-new-home/)). The new link is [sqlxevents.com](sqlxevents.com).

That bothers me is the sentence: "... The old methods (bitly and subdomain) will still be valid to point to the old landing page – for a time. ... ". Maybe it is good to add also the new link to the repository.

**Comment by ktaranov** [comment]
Hi @bogdandb , I will update resource with new link on Sunday, thanks for your suggestion.

**Comment by ktaranov** [comment]
Added via 8710687448a8301e87b480fc71b7fe0327513af6. Thanks for your contribution.
