### ISSUE TITLE
Red Gate Code link is dead, you are redirected to SQL Prompt which is paid

### ISSUE THREAD

**Issue by bogdandb** [ktaranov/sqlserver-kit#176]
https://github.com/ktaranov/sqlserver-kit/blob/master/SSMS/SSMS_Addins.md#sql-code-guard
Link is dead. Redirected to SQL Prompt (paid)

**Comment by ktaranov** [comment]
Thanks, Bogdan. Fixed via https://github.com/ktaranov/sqlserver-kit/commit/1ad56894197fc22b227d3cc0e7e4e705fdc789bd
