### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by bogdandb** [ktaranov/sqlserver-kit#183]
Link in section free courses [Learn SQL Server by solving problems (by Little Kendra)](https://sqlworkbooks.com/courses-overview/) is dead. I suppose that the proper link now is [LittleKendra.com (Courses)](https://littlekendra.com/courses-overview/) (or its equivalent)

**Comment by ktaranov** [comment]
Thanks! Fixed via https://github.com/ktaranov/sqlserver-kit/commit/a6c89cf4c8ef0cb22a653de134f7d699320133e8
