### ISSUE TITLE
Most ApexSQL Tools no longer free

### ISSUE THREAD

**Issue by LowlyDBA** [ktaranov/sqlserver-kit#187]
Relevant blog post: https://blog.apexsql.com/what-happened-to-the-apexsql-free-tools/

Only ApexSQL Plan & ApexSQL Snapshot Utility appear to be free, now. Which is a real shame.

**Comment by ktaranov** [comment]
> Only ApexSQL Plan & ApexSQL Snapshot Utility appear to be free, now. Which is a real shame.

Yep, agreed. Will fix during holidays.

**Comment by ktaranov** [comment]
Fixed via https://github.com/ktaranov/sqlserver-kit/commit/17c1a55e9e36882097d9498cd5ffb46e29021406
