### ISSUE TITLE
"Code" and "Abbreviation" meaning in "SQL Server Name Convention"

### ISSUE THREAD

**Issue by matteogll** [ktaranov/sqlserver-kit#188]
It's not clear to me the meaning of the following columns:

- Code
- Abbreviation

In the document "[SQL Server Name Convention and T-SQL Programming Style](https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Name%20Convention%20and%20T-SQL%20Programming%20Style.md)"

**Comment by ktaranov** [comment]
Hi, @matteogll 

Code - internal sql server column in `sys.objects` and others, determines type of object.

An abbreviation (from Latin brevis, meaning short[1]) is a shortened form of a word or phrase, for example, `FANG` - means acronym of Facebook Amazon Netflix Alphabet(Google).
