### ISSUE TITLE
Trace Flags for you collection

### ISSUE THREAD

**Issue by tboggiano** [ktaranov/sqlserver-kit#191]
https://support.microsoft.com/en-us/topic/kb4565944-improvement-a-manual-method-to-set-maximum-group-commit-time-in-sql-server-2017-13ef10f5-71d0-5873-0010-f5d1ad4798fe

These were added to support my company's environment they will coming to 2019 soon.

**Comment by ktaranov** [comment]
Wow, great thanks. @tboggiano  Could you add more information about `group commit`?

**Comment by tboggiano** [comment]
Yeah group commit description can found with its wait type here: https://www.sqlshack.com/sql-server-wait-type-hadr-group-commit/#:~:text=When%20multiple%20log%20records%20can%20be%20batched%20together,are%20expected%20and%20do%20not%20indicate%20an%20issue

**Comment by ktaranov** [comment]
@tboggiano great thanks for this information! Added via 3e61d9f56f4595d53bc52f5c5ba32f728ae069e4 and 2499eb36a7fae7544720ae8f326bb20befa65825
