### ISSUE TITLE
Trace Flag: 8048

### ISSUE THREAD

**Issue by erikdarlingdata** [ktaranov/sqlserver-kit#195]
There is incorrect information about TF 8048 in your document: "Note: Beginning with SQL Server 2014 SP2 and SQL Server 2016 this behavior is controlled by the engine and trace flag 8048 has no effect."

The trace flag does still has effect. The engine behavior will partition memory if CMEMTHREAD contention is detected. Turning on TF 8048 forces the partitioning without having to hit the internal thresholds.

**Comment by ktaranov** [comment]
@erikdarlingdata great thanks, fixed via https://github.com/ktaranov/sqlserver-kit/commit/51ccb46464fbc551f87fa0ae0e84f0888d41c956
