### ISSUE TITLE
Add trace flags 8670 and 1252

### ISSUE THREAD

**Issue by jobbish-sql** [ktaranov/sqlserver-kit#196]
Trace flag 8670 is mentioned here: https://www.sql.kiwi/2012/05/query-optimizer-deep-dive-part-4.html

Trace flag 1252 is totally unrelated and something that I found while fooling around. It prints some kind of lock related information when 3604 is also enabled. Don't know anything else. Example:

```
SELECT * FROM master..spt_values
OPTION (QUERYTRACEON 1252, QUERYTRACEON 3604);
```

**Comment by ktaranov** [comment]
Great thanks! Added via https://github.com/ktaranov/sqlserver-kit/commit/f57bc29cdc12859642419a92e2ef9e2a0a895f3b
