### ISSUE TITLE
Additional information for TF 2542 

### ISSUE THREAD

**Issue by jobbish-sql** [ktaranov/sqlserver-kit#197]
Information source: https://twitter.com/sqL_handLe

"SQL Server error log still tells you about the dump. But it never gets written."
"i should say, the error log still tells you about the stack text file, which still gets generated even with T2542 in place. Looks like that takes about 6 seconds rather than the dumps which were always over 1 minute."

He used it to resolve an issue where a production environment (with > 1 TB of RAM) was experiencing unhelpful memory dumps that would take more than 100 seconds to complete.  100 seconds is the max Availability Group lease timeout threshold.

**Comment by ktaranov** [comment]
Hi, @jobbish-sql , great thanks, could you add some details about using this flag? I added your description to file via https://github.com/ktaranov/sqlserver-kit/commit/d4d52461458d143678c03ff0d22d25e4dde09de8 but it still not clear for me how we can use this trace flag.
