### ISSUE TITLE
Trace flag 8099 should be 8101 ?

### ISSUE THREAD

**Issue by CrazySwimmer** [ktaranov/sqlserver-kit#211]
According to the KB article linked in the TF description, it is TF 8101 that should be used to enable the fix.

TF Description:
https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Trace%20Flag.md#8099

KB Article:
https://support.microsoft.com/en-us/topic/kb4538688-fix-severe-spinlock-contention-occurs-in-sql-server-2019-43faea65-fdcb-6835-f7fe-93abdb235837

**Comment by ktaranov** [comment]
Great thanks! Fixed via [5b779da](https://github.com/ktaranov/sqlserver-kit/commit/5b779da84abb9c73ecbead245d1a5498c1578628)
