### ISSUE TITLE
Database object naming convention

### ISSUE THREAD

**Issue by Deilan** [ktaranov/sqlserver-kit#215]
Regarding  [SQL Server Object Name Convention](https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Name%20Convention%20and%20T-SQL%20Programming%20Style.md#sql-server-object-name-convention) @ [SQL Server Name Convention and T-SQL Programming Style](https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Name%20Convention%20and%20T-SQL%20Programming%20Style.md):

> ## SQL Server Object Name Convention
> 
> | Object                                   | Code | Notation   | Length | Plural | Prefix  | Suffix | Abbreviation | Char Mask    | Example                              |
> |------------------------------------------|------| ---------- |-------:|--------|---------|--------|--------------|--------------|--------------------------------------|
> | [Database]                               |      | UPPERCASE  |     30 | No     | No      | No     | Yes          | [A-z]        | `MYDATABASE`                         |
> 

Could you please explain where this particular database naming convention comes from? I've never seen database named in UPPERCASE notation, nor I've seen any conventions proposing to name databases in uppercase. The most common case I'm aware of is to name in snake_case (`my_database` in this example). Even [the referenced article on database creation](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql) uses snake_case notation:
```sql
CREATE DATABASE database_name
```

**Comment by ktaranov** [comment]
It's just our choice, due to the convenience of reading large T SQL scripts - we want to see all changes and mentions of databases by capslock, it's convenient for us. You can use any notation in your team, the main thing is that everyone adheres to it.

**Comment by ktaranov** [comment]
Microsoft in its learning database recommended PascalCase notation.
