### ISSUE TITLE
Trace Flag 7412 is officially documented as having no effect in SQL Server 2019+, but not here

### ISSUE THREAD

**Issue by ReeceGoding** [ktaranov/sqlserver-kit#227]
[The documentation for Trace Flag 7412](https://learn.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-ver16) claims the following

> Starting with SQL Server 2019 (15.x), this trace flag has no effect because lightweight profiling is enabled by default.

I see nothing in this document that reflects this. For example, it's not in [the section for 7412](https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Trace%20Flag.md#trace-flag-7412) or the [list of recommended Trace Flags](https://github.com/ktaranov/sqlserver-kit/blob/master/SQL%20Server%20Trace%20Flag.md#recommended-trace-flags) (which includes 7412).

So who is wrong? This document or Microsoft's? I presume that someone with the relevant knowledge can test this and get a pull request in.

**Comment by Karambir06** [comment]
Just used old version SQL server

**Comment by ktaranov** [comment]
@ReeceGoding thanks! update info via https://github.com/ktaranov/sqlserver-kit/commit/1ea0afce75c40109d35b5e8b9f84dad897d0cc45
