### ISSUE TITLE
usp_BulkUpload: The module 'usp_BulkUpload' depends on the missing object

### ISSUE THREAD

**Issue by francescovista** [ktaranov/sqlserver-kit#79]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?** Problem during installation of the Stored Procedure

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com/** run the usp_BulkUpload.sql on a new server installation

**What is the expected behavior?** the stored procedure should install without problems 

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

SQL Server 2016
Windows10

**Comment by francescovista** [comment]
After I run the query

```
The module 'usp_BulkUpload' depends on the missing object 'dbo.usp_LogError'. The module will still be created; however, it cannot run successfully until the object exists.
The module 'usp_BulkUpload' depends on the missing object 'dbo.usp_PrintError'. The module will still be created; however, it cannot run successfully until the object exists.
```
![error](https://user-images.githubusercontent.com/30395256/29302062-124b4b9e-81d5-11e7-92ff-172beae74dd1.PNG)

**Comment by ktaranov** [comment]
@francescovista great thanks for your issuee, fixed: https://github.com/ktaranov/sqlserver-kit/commit/36f9e0a187a5dd49377718701f7547696105e323
Be free to post any new issue, pull request or just ask any question.
I will update this procedure with new SQL Server functionality: use in-memory tables if its possible due database properties and available memory
Thanks again.
