### ISSUE TITLE
SSMSBoost free version is now crippled after the trial period

### ISSUE THREAD

**Issue by Atario** [ktaranov/sqlserver-kit#95]
Regarding the listing in https://github.com/ktaranov/sqlserver-kit/blob/master/SSMS/SSMS_Addins.md

**Comment by ktaranov** [comment]
Hi, @Atario. You can get community license for free using: http://www.ssmsboost.com/generate-license-for-ssmsboost-ssms-add-in

**Comment by Atario** [comment]
The community license has recently changed and the feature set in it is greatly reduced now.

http://www.ssmsboost.com/VersionCompare

**Comment by ktaranov** [comment]
Thanks for link, not good news. But many nice features still present in free version and I think it is still must have addin for SQL Server.

Can I close this issue?

**Comment by Atario** [comment]
Well, I had hoped that the listing would be updated to reflect this change…

**Comment by ktaranov** [comment]
Fixed via https://github.com/ktaranov/sqlserver-kit/commit/5138fb74dabdf75b9afb56c50e3066d652bd5725

Great thanks for your detailed information. Be free open new issue or create pull request any time.
